### ISSUE TITLE
Upgrade fails 1.1.10~ynh1 -> 1.1.17~ynh2

### ISSUE THREAD

**Issue by Gredin67** [YunoHost-Apps/opensondage_ynh#89]
https://paste.yunohost.org/raw/buxejanujo

**Comment by zamentur** [comment]
I add the same bug (dubious ownership on composer) on an other instance with the same upgrade from the same version.
```
# yunohost --version
yunohost: 
  repo: stable
  version: 11.2.5
yunohost-admin: 
  repo: stable
  version: 11.2.3
moulinette: 
  repo: stable
  version: 11.2
ssowat: 
  repo: stable
  version: 11.2
```
