### ISSUE TITLE
Cannot create poll, phpmailer error?

### ISSUE THREAD

**Issue by eauchat** [YunoHost-Apps/opensondage_ynh#95]
### Context

- Hardware: *computer*
- YunoHost version: 11.2.9.1
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 1.1.19~ynh1

### Steps to reproduce

When creating a poll, everything's fine until I arrive to the last step and validate.
The request results in a 500 error.

Nginx logs contain the following:
```
2024/01/30 22:22:30 [error] 1718162#1718162: *154687 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PHPMailer\PHPMailer\Exception: SMTP Error: Could not connect to SMTP host. in /var/www/opensondage/vendor/phpmailer/phpmailer/src/PHPMailer.php:2157
Stack trace:
#0 /var/www/opensondage/vendor/phpmailer/phpmailer/src/PHPMailer.php(1981): PHPMailer\PHPMailer\PHPMailer->smtpConnect()
#1 /var/www/opensondage/vendor/phpmailer/phpmailer/src/PHPMailer.php(1653): PHPMailer\PHPMailer\PHPMailer->smtpSend()
#2 /var/www/opensondage/vendor/phpmailer/phpmailer/src/PHPMailer.php(1491): PHPMailer\PHPMailer\PHPMailer->postSend()
#3 /var/www/opensondage/app/classes/Framadate/Services/MailService.php(67): PHPMailer\PHPMailer\PHPMailer->send()
#4 /var/www/opensondage/create_date_poll.php(213): Framadate\Services\MailService->send()
#5 {main}
  thrown in /var/www/opensondage/vendor/phpmailer/phpmailer/src/PHPMailer.php on line 2157" while reading response header from upstream, client: XX.XXX.XX.XXX, server: domain.tld, request: "POST /create_date_poll.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.0-fpm-opensondage.sock:", host: "domain.tld", referrer: "https://domain.tld/create_date_poll.php"
```

Anyone has an idea of what may be going on?
Thanks for any suggestion :)

**Comment by dupdupf** [comment]
Hye

I'm in the exact same situation, have you found a solution since then?

**Comment by eauchat** [comment]
Nope, not yet :/

**Comment by alexAubin** [comment]
Discussion ongoing in https://forum.yunohost.org/t/new-survey-after-new-install-of-opensondage-delivers-only-empty-page/28055

**Comment by isAAAc** [comment]
same error here, 
old install failed, a fresh reinstall gives the same
```
root@krashboyz:/var/log# yunohost app info opensondage
description: Service for planning an appointment or making a decision quickly and easily
domain_path: date.krashboyz.org/
name: OpenSondage
version: 1.1.19~ynh3
root@krashboyz:/var/log# yunohost --version
yunohost: 
  repo: stable
  version: 11.2.10.3
yunohost-admin: 
  repo: stable
  version: 11.2.4.1
moulinette: 
  repo: stable
  version: 11.2
ssowat: 
  repo: stable
  version: 11.2
```
